baseURL = 'https://taure.github.io/novablog/'
languageCode = 'en-us'
title = 'Nova Framework Guide'
theme = 'hugo-book'

enableGitInfo = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
  [markup.highlight]
    style = 'monokai'
    noClasses = false

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = 'docs'
  BookSearch = true
  BookRepo = 'https://github.com/Taure/novablog'
  BookEditLink = '{{ .Site.Params.BookRepo }}/edit/main/{{ .Path }}'

[menu]
  [[menu.after]]
    name = 'Nova GitHub'
    url = 'https://github.com/novaframework/nova'
    weight = 1
  [[menu.after]]
    name = 'Nova Docs'
    url = 'https://hexdocs.pm/nova/quick-start.html'
    weight = 2
