baseURL = 'https://taure.github.io/novablog/'
languageCode = 'en-us'
title = 'Nova Framework Guide'
theme = 'PaperMod'
[pagination]
  pagerSize = 10

[params]
  author = 'Taure'
  description = 'A comprehensive guide to building web applications with the Nova Framework for Erlang'
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
  defaultTheme = 'auto'
  ShowToc = true
  TocOpen = false

  [params.homeInfoParams]
    Title = 'Nova Framework Guide'
    Content = 'A comprehensive tutorial series on building web applications with the Nova Framework for Erlang. From getting started to deployment.'

  [[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/Taure/novablog'

[menu]
  [[menu.main]]
    identifier = 'posts'
    name = 'All Posts'
    url = '/posts/'
    weight = 10
  [[menu.main]]
    identifier = 'tags'
    name = 'Tags'
    url = '/tags/'
    weight = 20

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = 'monokai'

[outputs]
  home = ['HTML', 'RSS']
