baseURL = 'https://taure.github.io/novablog/'
languageCode = 'en-us'
title = 'Nova Framework Guide'
theme = 'hextra'

enableRobotsTXT = true

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    identifier = 'guide'
    name = 'Guide'
    pageRef = '/docs'
    weight = 1
  [[menu.main]]
    name = 'Search'
    weight = 2
    [menu.main.params]
      type = 'search'
  [[menu.main]]
    name = 'GitHub'
    weight = 3
    url = 'https://github.com/novaframework/nova'
    [menu.main.params]
      icon = 'github'

[params]
  description = 'A comprehensive guide to building web applications with the Nova Framework for Erlang'

  [params.theme]
    default = 'system'
    displayToggle = true

  [params.navbar]
    displayTitle = true
    displayLogo = false

  [params.footer]
    enable = true
    displayCopyright = false
    displayPoweredBy = true

  [params.search]
    enable = true
    type = 'flexsearch'
    [params.search.flexsearch]
      index = 'content'
      tokenize = 'forward'

  [params.highlight.copy]
    enable = true
    display = 'hover'

  [params.page]
    width = 'wide'
